language: php

dist: focal

addons:
  postgresql: "13"
  apt:
    packages:
      - ldap-utils
      - slapd
      - postgresql-13
      - postgresql-client-13

services:
  - mysql
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

env:
  global:
    - IGNORE_PATHS=tests/sync_test.php
    - CODECHECKER_IGNORE_PATHS=$IGNORE_PATHS
    - PHPCPD_IGNORE_PATHS=$IGNORE_PATHS,locallib.php
    - PGVER=13

matrix:
  include:
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_311_STABLE
    - php: 8.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_400_STABLE
    - php: 8.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_401_STABLE
    - php: 8.0
      env: DB=pgsql MOODLE_BRANCH=master

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} -gt 7 ]]; then pecl install xmlrpc-beta; fi
  - echo 'max_input_vars=5000' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install
  - moodle-plugin-ci add-config '$CFG->auth = "manual,ldap";'
  - moodle-plugin-ci add-config 'define("TEST_AUTH_LDAP_HOST_URL", "ldap://localhost:3389");'
  - moodle-plugin-ci add-config 'define("TEST_AUTH_LDAP_BIND_DN", "cn=admin,dc=example,dc=com");'
  - moodle-plugin-ci add-config 'define("TEST_AUTH_LDAP_BIND_PW", "password");'
  - moodle-plugin-ci add-config 'define("TEST_AUTH_LDAP_DOMAIN", "dc=example,dc=com");'

before_script:
  - mkdir /tmp/slapd
  - slapd -f moodle/local/ldap/tests/fixtures/slapd.conf -h ldap://localhost:3389 &
  - sleep 3
  - ldapadd -H ldap://127.0.0.1:3389 -D "cn=admin,dc=example,dc=com" -w password -f moodle/local/ldap/tests/fixtures/bootstrap.ldif

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
